UNIQUE_MAPPINGS = {
    "lore related to one terrain inhabited by animals you like (such as plains lore or swamp lore).": "specific terrain lore",
    "lore related to one city you've visited often.": "specific settlement lore",
    "lore related to the terrain you lived in as a hermit (such as cave lore or desert lore).": "specific terrain lore",
    "lore related to one terrain you scouted in (such as forest lore or cavern lore).": "specific terrain lore",
    "lore for the city you lived in as a street urchin (such as absalom lore or magnimar lore).": "specific settlement lore",
    "lore thematically associated with the members of the ancestry you grew up with: dwarf, elf, gnome, goblin, or halfling.": "specific ancestry lore",
    "lore related to the terrain type associated with your home region (such as hills lore or mountains lore)": "specific terrain lore",
    "lore related to one plane of your choice (other than the material plane).": "specific plane lore",
    "lore skill with a subcategory associated with your deity (abadar lore, for instance).": "specific deity lore",
    "lore related to a particular kind of common animal (such as equine lore, feline lore, or pachyderm lore)": "specific animal lore",
    "elemental lords lore or a lore skill related either to one of the elemental planes (such as plane of air lore).": "specific plane lore",
    "lore related to the terrain you lived in while on the demiplane (such as cave lore or desert lore).": "specific terrain lore",
    "lore related to the terrain you worked in (such as desert lore or plains lore).": "specific terrain lore",
    "lore for the city in which you were raised.": "specific settlement lore",
    "lore related to your deity or cult.": "specific deity lore",
    "lore for your patron deity.": "specific deity lore",
    "lore related to the settlement you came from.": "specific settlement lore",
    "lore for the settlement you grew up scavenging in.": "specific settlement lore",
    "lore for the settlement that employed you.": "specific settlement lore",
    "skill appropriate for the terrain around your community (such as forest lore or jungle lore) lore": "specific terain lore",
    "lore for the creature associated with your contacted eidolon (such as angel lore or dragon lore).": "specific creature type lore",
    "lore of your choice": "any specific lore",
    "lore associated with the chosen energy (such as fire lore)": "specific energy lore",
    "lore for the deity you worship. ": "specific deity lore",
    "lore of the terrain in which you scavenge.": "specific terrain lore",
    "lore of your choice.": "any specific lore",
    "lore specializing in one local type of undead.": "specific undead lore",
    "lore associated with the deity you preach for (such as pharasmin lore).": "specific deity lore",
    "mana wastes lore (or another similar lore skill associated with the wastes where you grew up).": "mana wastes lore",
    "lore for your home settlement.": "specific settlement lore",
    "lore with one of geb's cities: graydirge, mechitar, or yled.": ["graydirge lore", "mechitar lore", "yled lore"],
    "lore associated with a particular type of wilderness (choose from forest, hills, mountains, plains, rivers, or swamp).": ["forest lore", "hills lore", "plains lore", "rivers lore", "swamp lore"],
    "lore for a specific settlement or terrain you have traveled through.": ["specific settlement lore", "specific terrain lore"],
    "lore for the city in which you were a messenger.": "specific settlement lore",
    "lore about a specific terrain, as befits where you spent most of your childhood growing up.": "specific terrain lore",
    "lore as fits your history: daemon lore, demon lore, or devil lore. you also gain the following free action.": ["daemon lore", "demon lore", "devil lore"],
    "lore skills associated with a profession, as befits your history: art lore, engineering lore, farming lore, herbalism lore, labor lore, mercantile lore, scribing lore, theater lore, or warfare lore. ": ["art lore", "engineering lore", "farming lore", "herbalism lore", "labor lore", "mercantile lore", "scribing lore", "theater lore", "warfare lore"],
    "one or more lore skills related to a specific plane +14": "specific plane lore",
    "one additional lore +14": "any specific lore",
    "- (understands its creator)": "creator",
    "(can\u2019t speak any language)": "all",
    "telepathy 100 feet": "telepathy",
    "(or undercommon, for darklands variants)": "Undercommon",
    "telepathy (touch)": "telepathy",
    "three additional mortal languages; telepathy 100 feet, tongues": ["any", "telepathy", "tongues"],
    "telepathy 100 feet, tongues": ["telepathy, tongues"],
    "two other languages": "any",
    "one elemental language (aquan, auran, ignan, or terran), one planar language (abyssal, celestial, or infernal); telepathy 100 feet": ["aquan", "auran", "ignan", "terran", "abyssal", "celestial", "infernal", "telepathy"],
    "(can\u2019t speak)": "none",
    "(can\u2019t speak any language); master link": "creator",
    "speak with plants (trees only)": "speak with plants",
    "speak with plants (gourds only)": "speak with plants",
    "speak with plants (fungi only)": "speak with palnts",
    "plus any one ancient language": "any",
    "plus any two ancient languages": "any",
    "telepathy 30 feet": "telepathy",
    "(can't speak any language); telepathy 100 feet": "telepathy",
    "shark commune 150 feet": "shark commune",
    "telepathy 120 feet": "telepathy",
    "one spoken by its creator (typically common)":"any",
    "comprehend language":"any",
    "plus two others": "any",
    "telepathy 300 ft.": "telepathy",
    "plus one regional language": "any",
    "telepathy 1 mile": "telepathy",
    "can't speak any language": "none",
    "and other languages typical to the region": "any",
    "one or more planar languages; tongues": ["abyssal", "celestial", "infernal", "tongues"],
    "(can't speak any language)": "none",
    "(can speak pre-recorded phrases only)": "unique",
    "(can't speak any languages)": "none",
    "one regional language (can't speak any language)": "any",
    "telepathy 120 feet, tongues": ["telepathy", "tongues"],
    "(can't speak any languages); telepathy 100 feet": "telepathy",
    "can't speak": "none",
    "carbuncle empathy 30 feet": "carbuncle empathy",
    "can speak only destrachan": "destrachan",
    "can't speak any language; telepathy 100 feet":"telepathy",
    "can't speak any language, telepathy 100 feet":"telepathy",
    "can't speak any languages; telepathy 100 feet":"telepathy",
    "speak with plants (sunflowers only)": "speak with plants",
    "speak with plants (carnivorous plants only)": "speak with plants",
    "one additional language (usually gnoll)": "any",
    "telepathy 1 mile (other moonflowers only)": "telepathy",
    "see planar incarnation": ["abyssal", "celestial", "infernal"],
    "telepathy (touch only)": "telepathy",
    "telepathy 100 ft.":"telepathy",
    "any one ancient language (such as jistkan)":"any",
    "any one spoken in life by their murderer (typically common)": "any",
    "telepathy 100 feet (with spectral thralls only)":"telepathy",
    "tongues (can speak only through simulacra)": "tongues",
    "telepathy 80 feet": "telepathy",
    "telepathy 100 feet, universal language": "telepathy",
    "telepathy 60 feet": "telepathy",
    "indomitable oration, telepathy 100 feet": "telepathy",
    "telepathy 100 feet; tongues": ["telepathy", "tongues"],
    "absorbed language":"any",
    "languages spoken by the adventurers (typically common, dwarven, elven, and goblin)": "any",
    "speak with plants, telepathy 50 feet": ["speak with plants", "telepathy"],
    "speak with plants, telepathy 150 feet": ["speak with plants", "telepathy"],
    "speak with plants (plants with vines only)":"speak with plants",
    "speak with plants (succulents only)":"speak with plants",
    "speak with plants (seaweed only)":"speak with plants",
    "telepathy 30 feet (munavris only)":"telepathy",
    "telepathy 100 feet (myceloids and those afflicted by purple pox only)":"telepathy",
    "(can't speak any language); telepathy 300 feet":"telepathy",
    "(can't speak any language); telepathy 200 feet":"telepathy",
    "(can't speak any language); telepathy 500 feet":"telepathy",
    "(can't speak any language), telepathy 500 feet":"telepathy",
    "no voice; tongues":"tongues",
    "20 other languages; telepathy 100 feet":["any", "telepathy"],
    "telepathy 200 feet": "telepathy",
    "(understands commands)":"unique",
    "telepathy 60 feet, tongues":["telepathy", "tongues"],
    "(can speak and understand only simple words)":"unique",
    "speak with animals, speak with plants, telepathy 300 feet": ["speak with animals", "speak with plants", "telepathy"],
    "(can't speak any language), telepathy 60 feet":"telepathy",
    "(can't speak)":"none",
    "one language depending on its mortal life; telepathy 30 feet":["any", "telepathy"],
    "speak with animals, telepathy 100 feet":["speak with animals", "telepathy"],
    "telepathy telepathy 100 feet (idovik only)":"telepathy",
    "telepathy 100 feet (ashen swale only)":"telepathy",
    "insect empathy, telepathy 120 feet":["insect empathy", "telepathy"],
    "plus any one language spoken in life (can't speak any language)":["any"],
    "plus any four languages (typically ancient languages)":"any",
    "one other language":"any",
    "one planar language (typically aquan, auran, ignan, or terran)":"any",
    "plus any one language":"any",
    "one additional language":"any",
    "plus any one language they knew while alive":"any",
    "plus any two languages they knew while alive":"any",
    "any one language known by the polong's creator":"any",
    "any one language spoken in life by their murderer (typically common)":"any",
    "any one spoken in life by their murderer (typically common; can't speak)":"any",
    "telepathy 300 feet":"telepathy",
    "telepathy 300 feet, tongues":["telepathy", "tongues"],
    "(can't speak any language), telepathy 100 feet":"telepathy",
    "(can't speak any language), telepathy 300 feet":"telepathy",
    "any languages spoken by its preserved heads":"any",
    "(can't speak any language), undead master link":"creator",
    "(can't speak any language); convergent link":"convergent link",
    "(can't speak any language); telepathy 60 feet":"telepathy",
    "(cannot speak any language)":"none",
    "(cannot read)":"none",
    "telepathy (with its creator only) 100 feet":"telepathy",
    "up to four others":"any",
    "plus any two ancient languages (can't speak)":"any",
    "plus any two ancient languages; telepathy (30 feet)":["any", "telepathy"],
    "(can't speak any language; telepathy 100 feet, images only)":"telepathy",
    "immolis; telepathy 100 feet":["immolis","telepathy"],
    "one other language; telepathy 100 feet":["any", "telepathy"],
    "object immunities": ["bleed", "death", "disease", "positive", "mental", "nonlethal", "poison", "doom", "drain", "fatigue", "paralysis", "sick", "unconscious"],
    "precision damage": "precision",
    "cold ;": "cold",
    "critical hits (except bludgeoning or sonic )": "critical",
    "precision damage.": "precision",
    "death effects":"dying",
    "paralyzed":"paralysis",
    "physical damage": ["blugeoning", "piercing", "slashing"],
    "object immunities (except mental effects)": ["bleed", "death", "disease", "positive", "nonlethal", "poison", "doom", "drain", "paralysis", "sick"],
    "fire damage": "fire",
    "object immunities (except positive )": ["bleed", "death", "disease", "mental", "nonlethal", "poison", "doom", "drain", "fatigue", "paralysis", "sick", "unconscious"],
    "non- magical attacks": "non-magical",
    "controlled":"control",
    "doomed":"doom",
    "drained":"drain",
    "fatigued":"fatigue",
    "healing":"positive",
    "nonlethal attacks":"nonlethal",
    "sickened":"sick",
    "confused":"confusion",
    "magic (see below)": "magic",
    "death":"dying",
    "area damage":"area",
    "effects that would transform their body or soul to an undead":"undead",
    "blinded":"blind",
    "dazzled":"dazzle",
    "deafened":"deaf",
    "negative energy": "negative",
    "paralyze":"paralysis",
    "critical hits (except bludgeoning or sonic)": "critical",
    "enfeebled":"enfeeble",
    "persistent damage": "presistent",
    "petrified":"petrify",
    "stupefied":"stupify",
    "misfortune effects": "misfortune",
    "light":"positive",
    "swarm attacks": "swarm",
    "enfeebled (while wearing its mask)": "enfeeble",
    "slowed (while wearing its mask)": "slow",
    "magic (see golem antimagic below)": "magic",
    "petrification": "petrify",
    "electricity (see lightning drinker)": "electricity",
    "stunned": "stun",
    "fire (see below)": "fire",
    "death effects (except necrotic decay)": "dying",
    "poisoned": "poison",
    "curses": "curse",
    "diseased":"disease",
    "scrying":"scry",
    "unconsciousness": "unconscious",
    "good damage":"good",
    "lawful damage": "lawful",
    "grabbed": "grab",
    "immobilized": "immobilize",
    "vision-based effects": "vision",
    "emotion effects": "emotion",
    "shadow (see one with shadows)": "shadow",
    "frightened": "fear",
    "critical hits (except slashing)": "critical",
    "ingested  poisons": "poison",
    "olfactory effects":"olfactory",
    "olfactory e": "olfactory",
    "and unconscious":"unconscious",
    "disease paralyzed":"paralysis",
    "magic (below)": "magic",
    "a <%SKILLS%8%%>Lore<%END> related either to one of Elemental Planes (such as <%PLANES%4%%>Plane of Air<%END> Lore).": "specific plane lore",
    "Lore related to terrain you lived in while on demiplane (such as <%SKILLS%8%%>Cave Lore<%END>": "specific terrain lore",
    "<%SKILLS%8%%>Desert Lore<%END>).": "desert lore",
    "Lore as fits your history: <%MON.FAMILY%26%%>Daemon<%END> Lore": "daemon lore",
    "<%MON.FAMILY%28%%>Demon<%END> Lore": "demon lore",
    "<%MON.FAMILY%30%%>Devil<%END> Lore. You also gain following free action.": "devil lore",
    "more Lores related to a specific plane +14": "specific plane lore"

}

LORE_LIST = ['lore', 'scribing lore', 'circus lore', 'guild lore', 'art lore', 'alcohol lore', 
             'legal lore', 'underworld lore', 'theater lore', 'farming lore', 'warfare lore', 
             'fortune-telling lore', 'games lore', 'gladiatorial lore', 'herbalism lore', 
             'tanning lore', 'labor lore', 'mercantile lore', 'mining lore', 
             'sailing lore', 'engineering lore', 'academia lore', 'heraldry lore',
             'hunting lore', 'dragon lore', 'kintargo lore', 'dahak lore', 'architecture lore', 
             'breachill lore', 'darklands lore', 'jungle lore', 'politics lore', 
             'pathfinder society lore', 'business lore', 'government lore', 'absalom lore', 
             'animal lore', 'ocean lore', 'razmir lore', 'abyssal lore', 'alchemical lore',
             'orc lore', 'forest lore', 'undead lore', 'mercenary lore', 'curse lore', 
             'sarkorian history lore', 'desert lore', 'ancient osirion lore', 'anatomy lore', 
             'assassin lore', 'azlant lore', 'weather lore', 'wilderness lore', 'ooze lore', 
             'abyss lore', 'mzali lore', 'shory lore', 'swamp lore', 'westcrown lore', 'goblin lore', 
             'shadow plane lore', 'hell lore', 'quah lore', 'thassilon lore', 'revolution lore', 
             'kalistrade lore', 'spirit lore', 'droskar lore', 'portal lore', 'genealogy lore', 
             'rope lore','crowd lore', 'clown lore', 'scam lore', 'zevgavizeb lore', 
             'thassilonian history lore', 'demon lore', 'aspis consortium lore', 'surgery lore', 
             'accounting lore', 'cooking lore', 'plains lore', 'harrow lore', 'library lore', 
             'cartography lore', 'kobold lore', 'fleshwarp lore', 'otari lore', 'roseguard lore', 
             'astrology lore', 'wisp lore', 'goka lore', 'magaambya lore', 'nantambu lore', 'insect lore', 
             'music lore', 'plant lore', 'fortune-teller lore', 'genie lore', 'magical terrain lore', 
             'cryptography lore', 'piloting lore', 'scouting lore', 'boneyard lore', 'hillcross lore', 
             'herding lore', 'brigh lore', 'firearm lore', 'alkenstar lore', 'necromancy lore', 'funeral lore', 
             'crimson reclaimers lore', 'shining sentinels lore', 'zombie lore', 'urgathoa lore', 
             'dreamlands lore', 'planar rift lore', 'star lore', 'banditry lore', 'gladiator lore', 
             'stabling lore', 'firebrand lore', 'acting lore', 'fleshforged lore', 'axis lore', 'vampire lore', 
             'geology lore', 'elemental lore', 'dwelling lore', 'fire lore', 'cult lore', 'iruxi lore', 
             'heaven lore', 'skeletal lore', 'bardic lore', 'spider lore', 'torture lore', 'ancient history lore', 
             'gambling lore', 'cave lore', 'elysium lore', 'styx lore', 'gold lore', 'astronomy lore', 
             'planar lore', 'abaddon lore', 'gem lore', 'sea lore', 'black desert lore', 'daemon lore', 
             'local court lore', 'map lore', 'scouting lore', 'plague lore', 'household lore', 
             'graveyard lore', 'fishing lore', 'monster lore', 'geography lore', 'smithy lore',
             'bureaucracy lore', 'shining crusade lore', 'xulgath lore', 'norgorber lore', 'maelstrom lore',
             'dream lore', 'purpose lore', 'devil lore', 'yioxat tribe lore', 'nirvana lore', 
             'plane of fire lore', 'jewelry lore', 'art lore', 'settlement lore', 'plane of air lore', 
             'dungeon lore', 'plane of earth lore', 'plane of water lore', 'positive energy plane lore', 
             'dark tapestry lore', 'meteorology lore', 'festival lore', 'monastic lore', 'ruins lore', 
             'millinery lore', 'manticore lore', 'midwifery lore','dimension of time lore', 
             'confectionery lore', 'haunt lore', 'martial arts lore', 'irori lore','temple lore', 
             'wrestling lore', 'crime lore', 'flying mountains lore', 'dancing lore', 'demiplane lore', 
             'azlanti lore', 'ekujae lore', 'slaver lore', 'aiudara lore', 'saggorak lore','kovlar lore', 
             'katapesh lore', 'hermea lore', 'ruby phoenix tournament lore', 'weapons lore','grave lore', 
             'deity lore', 'ghol-gan lore', 'walkena lore', 'mwangi expanse lore','first world lore', 
             'saga lands lore', 'jistka lore', 'underwater lore', 'shadow lore', 'mammoth lord lore',
             'negative energy plane lore', 'driving lore', 'soothsaying lore', 'ghost lore', 
             'nethys lore', 'kazutal lore', 'woodland lore', 'brewing lore', 'banking lore', 
             'gunpowder lore', 'blood lore', 'spellscar desert lore', 'spellscar lore', 'nex lore',
             'geb lore', 'abberton lore', 'gozreh lore', 'criminal lore', 'aroden lore', 'ludovica lore',
             'esoteric lore', 'graydirge lore', 'poison lore', 'local lore', 'sallowshore lore', 
             'twilight castrum lore', 'holomog lore', 'dinosaur lore', 'willowside lore', 'shraen lore',
             'kabriri lore', 'secret eater lore', 'mechitar lore', 'yogsothoth lore', 'brevoy lore',
             'restov lore', 'lumber lore', 'river lore', 'nobility lore', 'gorum lore', 'fey lore',
             'giant lore', 'hill lore', 'architectural lore', 'sewing lore', 'first world\xa0lore', 
             'lamashtu lore', 'star lore', 'arctic lore']

DAMAGE_TYPE = ["blugeoning", "piercing", "slashing", "acid", "cold", "electricity", "fire", "sonic",
               "positive", "negative", "force", "chaotic", "evil", "good", "lawful", "mental",
               "precision", "cold iron", "orichalcum", "silver", "nonlethal", "critical", "precision",
               "non-magical", "magic", "area", "swarm"]

STATUS_TYPE = ["doom", "dying", "unconscious", "wounded", "bleed", "death", "disease", "poison",
                "drain", "fatigue", "paralysis", "sick", "control", "emotion", "fear", "swarm mind",
                "confusion", "calcification", "ward contract", "sleep", "polymorph", "curse", "visual",
                "undead", "blind", "dazzle", "deaf", "spell deflection", "clumsy", "enfeeble", "presistent",
                "petrify", "stupify", "misfortune", "olfactory", "slow", "possession", "flat-footed", "stun",
                "persistent wassailing", "skeleton crew", "detection", "scry", "evocation", "grab", "prone",
                "immobilize", "charm", "air", "trip", "extradimensional", "keeper of the lighthouse",
                "vision", "radiation", "darkness", "shadow", "divination", "nameless nightmare", ]

KEYS_TO_KEEP = ['category', 'feat', 'level', 'pfs', 'rarity', 'resistance', 'source', 'source_category',
                'speed', 'trait', 'type', 'weakness', 'actions','frequency','skill','archetype',
                'school','source_group','ability','ability_flaw','language','size','vision',
                'archetype_category','damage','damage_die','deity','hands','item_category','item_subcategory',
                'weapon_category','weapon_group','weapon_type','bulk','ammunition','reload','ac','complexity',
                'disable','fortitude_save', 'ac', 'range', 'price', 'hp', 'cost', 'hardness', 'hazard_type',
                'immunity','reflex_save','stealth','will_save','region','trait_group','duration','onset',
                'saving_throw','alignment','spell','cleric_spell','divine_font','domain', 'domain_alternate', 
                'domain_primary', 'follower_alignment','charisma','constitution','dexterity','intelligence',
                'perception','sense','strength','strongest_save','weakest_save','wisdom','creature_family',
                'armor_category','armor_group','dex_cap','check_penalty','speed_penalty','attack_proficiency',
                'defense_proficiency','fortitude_proficiency','perception_proficiency','reflex_proficiency',
                'skill_proficiency','will_proficiency','bloodline','component','heighten_level','tradition',
                'heighten','mystery','lesson','patron_theme']